# Copyright 2020 dylan
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
options:
  alertmanager_image_path:
    default: 'quay.io/prometheus/alertmanager'
    description: The docker image to use
    type: string
  pagerduty_key:
    default: ''
    type: string
